package:
  name: elaspic-rest-api
  version: "0.1.3"

source:
  path: ../../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    # Webserver packages
    - aiofiles =0.5
    - aiohttp =3.7
    - aiomysql =0.0.20
    - bleach =3.2
    - fastapi =0.61
    - fire =0.3
    - gunicorn =20.0
    - jinja2 =2.11
    - sentry-sdk =0.19
    - uvicorn =0.11
    # Bioinformatics packages
    - kmbio =2.1.0
    - kmtools =0.2.8
    - mysqlclient =2.0

test:
  imports:
    - elaspic_rest_api

about:
  home: https://gitlab.com/elaspic/elaspic-rest-api
  license: MIT License
  summary: "ELASPIC REST API"
